Update azure-webapps-php.yml

diff --git a/.github/workflows/azure-webapps-php.yml b/.github/workflows/azure-webapps-php.yml
--- a/.github/workflows/azure-webapps-php.yml
+++ b/.github/workflows/azure-webapps-php.yml
@@ -1,41 +1,47 @@
 name: PHP Syntax Check
 
-on: [push, pull_request]
+on:
+  push:
+    branches:
+      - master
+  pull_request:
+    branches:
+      - master
 
 jobs:
   phplint:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Setup PHP
-      uses: shivammathur/setup-php@v2
-      with:
-        php-version: '7.4'
+      - name: Setup PHP
+        uses: shivammathur/setup-php@v2
+        with:
+          php-version: '7.4'
 
-    - name: Get list of changed files
-      id: changed-files
-      run: |
-        git fetch origin master:refs/remotes/origin/master
-        git diff --name-only origin/main ${{ github.sha }} > all_changed_files.txt
-        echo "All changed files:"
-        cat all_changed_files.txt
+      - name: Get list of changed files
+        id: changed-files
+        run: |
+          git fetch origin master:refs/remotes/origin/master
+          git diff --name-only origin/master ${{ github.sha }} > all_changed_files.txt
+          echo "All changed files:"
+          cat all_changed_files.txt
 
-    - name: Filter PHP files
-      run: |
-        grep '\.php$' all_changed_files.txt > changed_files.txt || echo "No PHP files changed or an error occurred."
-        echo "Filtered PHP files:"
-        cat changed_files.txt
+      - name: Filter PHP files
+        run: |
+          grep '\.php$' all_changed_files.txt > changed_files.txt || echo "No PHP files changed or an error occurred."
+          echo "Filtered PHP files:"
+          cat changed_files.txt
 
-    - name: Run PHP Lint
-      run: |
-        if [ -s changed_files.txt ]; then
-          while IFS= read -r file; do
-            echo "Checking syntax for $file"
-            php -l "$file"
-          done < changed_files.txt
-        else
-          echo "No PHP files changed."
-        fi
+      - name: Run PHP Lint
+        run: |
+          if [ -s changed_files.txt ]; then
+            while IFS= read -r file; do
+              echo "Checking syntax for $file"
+              php -l "$file"
+            done < changed_files.txt
+          else
+            echo "No PHP files changed."
+          fi
