Update azure-webapps-php.yml

diff --git a/.github/workflows/azure-webapps-php.yml b/.github/workflows/azure-webapps-php.yml
--- a/.github/workflows/azure-webapps-php.yml
+++ b/.github/workflows/azure-webapps-php.yml
@@ -21,11 +21,32 @@ jobs:
       with:
         php-version: '7.4'  # hoặc phiên bản PHP mà dự án của bạn sử dụng
 
+    - name: Check PHP version
+      run: php -v
+
+    - name: Install Composer
+      run: |
+        EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
+        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+        ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+        if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
+            >&2 echo 'ERROR: Invalid installer signature'
+            rm composer-setup.php
+            exit 1
+        fi
+        php composer-setup.php --install-dir=/usr/local/bin --filename=composer
+        rm composer-setup.php
+        composer self-update --2.2
+
     - name: Install dependencies
       run: |
         sudo apt-get update
         sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev
-        docker-compose up -d
+        composer install
+
+    - name: Start Docker Compose
+      run: |
+        docker-compose -f path/to/your/docker-compose.yml up -d  # Cập nhật đường dẫn nếu cần
         sleep 15  # Chờ cho Docker container khởi động
 
     - name: Run tests
